# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, verbose_name='ip')),
                ('host_name', models.CharField(max_length=128, verbose_name='主机名')),
                ('os', models.CharField(max_length=128, verbose_name='操作系统')),
                ('cpu', models.CharField(max_length=128, verbose_name='cpu型号')),
                ('last_login_time', models.CharField(max_length=128, verbose_name='上次登录时间')),
                ('is_delete', models.BooleanField(verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '主机表',
                'verbose_name_plural': '主机表',
            },
        ),
    ]
